### ISSUE TITLE
Allow to go back in history in imerge 

### ISSUE THREAD

**Issue by maloy-ghosh** [mhagger/git-imerge#102]
Say I am middle of a imerge session. There was one conflict in one intermediate stage. I resolve conflict, commit and then continue git-imerge. Now imerge presents the next conflict stage. Here I screw  up something and make a wrong commit and say even instructed imerge to continue.

Now my question is how to go back to the good intermediate stage (good commit) and start imerge from there. Right now I can reset my head to the good commit, but when I instruct imerge to continue it fails with "<Good commit> was not blocking the frontier." So how to go back in time in imerge seesions?

Otherwise please tell me if I could do things differently. I see a command "remove". Is it supposed to help in this situation?

**Comment by mhagger** [comment]
There is currently no support for redoing a merge that was done incorrectly the first time. I *think* it should be sufficient to delete any references named `refs/imerge/<name>/{auto,manual}/<I>-<J>` where `I` and `J` are integers greater than or equal to the `(I,J)` of the commit that you want to redo, then run `git imerge continue`. But there is also a `blockers` field in the blob pointed at by `refs/imerge/<name>/state` that might cause problems in some situations, and there might be other loose ends that I haven't thought of. Try it and see, and let us know what you find out.

It would be nice to have a command to do this, but I don't know of anybody working on it.

The `remove` command removes the entire imerge. That's not what you want.
