### ISSUE TITLE
The history is not linear?

### ISSUE THREAD

**Issue by therealprof** [mhagger/git-imerge#110]
I'm having a few troubles using git-imerge to merge a new baseline release into a customer specific branch whereas a regular git merge works just fine.

The situation looks something like this:

```
o---o---A---B---C---D---E---F---G    releases/master-2.3
         \               \
  o---o---o---o---o---o---o---o      customer/foo
```

Now I have to merge a tagged version from the releases branch into (actually a number of) customer branch. So A already has been merged a while in the past and a few customer specific changes had been made meanwhile but now I'm looking into merging E.

With git itself it's just a matter of doing:
`git merge <tag equivalent to E>`
and fixing a few conflicts.

However with git-imerge I get lots of complaints (after fixing the interpolation problems) but no merge:

```
# git imerge init --name customer-foo-E E 
usage: git-imerge [-h]
                  {start,merge,rebase,drop,revert,continue,finish,diagram,list,init,record,autofill,simplify,remove,reparent}
                  ...
git-imerge: error: The history "69e19f5b000a22159b4c8a3a167890051f1d6999..customer/foo" is not linear
Perhaps use "--first-parent"?
```

With _--first-parent_ I get:

```
# git imerge init --name customer-foo-E --first-parent E
Commit "69e19f5b000a22159b4c8a3a167890051f1d6999" is not a first-parent ancestor of "customer/foo"
```

69e19f5b000a22159b4c8a3a167890051f1d6999 is correctly identified as the last merge point (**A** in the diagram) but it still fails to merge the commits B, C, D, E into the customer branch.

Just for kicks I tried checking out the release branch and using git-inmerge to merge the customer branch in but I get the exact same complaints.

Manually it's rather easy to figure out that all changes between the merge commit on the customer branch where **A** was merged in and HEAD (the rows for imerge) and all changes between **A** and **E** (the columns for imerge) should be used but how to tell imerge?

**Comment by orao** [comment]
This seems related to issue #107.

**Comment by mhagger** [comment]
Thanks for your clear description (and ASCII-art, my favorite!) of the problem and how it arises in a common workflow. This is a dup of #107, so let's continue discussion there.
