### ISSUE TITLE
Problem with complex merge

### ISSUE THREAD

**Issue by mgorovoy** [mhagger/git-imerge#113]
I am working on a project with codebase that got severely diverged. The new release branches have been created from the previous release branches for a number of iterations, with all except the last one merged (manually) into development branch that may include some intermediate commits (see the diagram below). I wanted to try using git-imerge to perform merge of the latest un-merged release branch into development branch, but discovered that no matter what combination of arguments I've tried it would not work. Please let me know whether this could be done.

     -A-.-.-.-.-.-.-.-.-.-.-.-.-.-.-Ae-.-.-.-.-.-.-.-.-.-Af-.-.-.-.-*
         \                          /                   /          /
          -B-.-.-.-Bg-.-.-.-Bh-.-.-Bi                  /          ?
                    \        \      \                 /          /
                     -C-.-.-.-Cj-.-.-Ck-.-.-Cm-.-.-.-Cn         ?
                                             \        \        /
                                              --Do-.-.-Dp-.-.-Dq

**Comment by mgorovoy** [comment]
Here is the error message that I get:

    (development) $git imerge start --name=dev60 --first-parent release/6.0
    There are no commits on "development" that are not already in "release/6.0"

**Comment by mhagger** [comment]
It would be a lot easier to diagnose your problem with access to your repository. Is it publicly available? If not, could you anonymize it using `git fast-export --anonymize` and make the anonymized repository available? If so, please let us know where to find the repo and exactly what `git imerge` command line to use to provoke the problem.

I don't have any idea if it would help, but have you tried running this using branch `loosen-first-parent-rule` from PR #111?

**Comment by mhagger** [comment]
No response → closing issue. Feel free to reopen if you can provide more information.
