### ISSUE TITLE
merge fails with the message Commit "xx" is not a first-parent ancestor of "develop"

### ISSUE THREAD

**Issue by GeirGrusom** [mhagger/git-imerge#115]
git-imerge merge --name merge-develop-master master

Immediately fails with the message described above.

git-imerge 1.0.0
Windows 10, git version 2.10.2.windows.1

I can't publish the repository, and I have no idea why the error occurs.

> Commit "12ea382718bce22108b1a27c7e2a25602dc31977" is not a first-parent ancestor of "develop"

But `git merge-base --all --fork-point master`
says that `12ea382718bce22108b1a27c7e2a25602dc31977` is the correct first parent ancestor.

**Comment by GeirGrusom** [comment]
I managed to get around this by producing a new branch which merged early commits past the two different convergent points suggested by git-log and git-imerge.

**Comment by mhagger** [comment]
@GeirGrusom: Could you try your failing merge with the branch from this PR: #111? I think it will fix your problem, but I'm having trouble getting people to test it so that I can merge it confidently.

**Comment by GeirGrusom** [comment]
@mhagger That branched solved my issue! Great work!

**Comment by godfat** [comment]
I got the same error with 1.0.0. Tried master and it worked now. Could you please release a new version? Thanks!

**Comment by danielpcox** [comment]
Same here. `master` behaves well, but the released version fails with "not a first-parent ancestor".

**Comment by mhagger** [comment]
:white_check_mark: Release [released](https://github.com/mhagger/git-imerge/releases/tag/v1.1.0). Yeah, that was overdue.

**Comment by jalanb** [comment]
Upgrading to version 1.1, to include @GeirGrusom's fix, also solved my problem

```sh
$ git-imerge rebase --goal rebase python3
Commit "c86b08276050432fa172fde9df7bf02703146ba2" is not a first-parent ancestor of "python3"
$ brew upgrade git-imerge
Updating Homebrew...
==> Upgrading 1 outdated package, with result:
git-imerge 1.0.0 -> 1.1.0
...
$ git-imerge rebase master
The following commits on the to-be-merged branch are merge commits:
    f448fa66b4cbddf9dd1525cb68bf5e5f656acd68
--goal='rebase' is not yet supported for branches that include merges.
```
And ran into other problems after that, but it did fix the `not a first-parent ancestor` issue (for any passing Googlers
