### ISSUE TITLE
Is there a way to `finish` a partial merge?

### ISSUE THREAD

**Issue by dcci** [mhagger/git-imerge#121]
I'm merging an upstream opensource branch in my downstream tree.
In the process of doing that, I realized I needed to do some changes, and I wanted to stop the merge where it is right now

```
commit ba81bfb7cc8a1bae4cc5fb770cb098f896fede96
Merge: 272d5b7 ea96306
Author: Davide Italiano <dccitaliano@gmail.com>
Date:   Thu Mar 9 11:35:50 2017 -0800

    imerge 'mymerge': manual merge 1-649
    
    # Conflicts:
    #   lld/ELF/Driver.cpp

commit 272d5b79f115508869ec90a32b9f42dcd66d462e
Merge: 3cc4f96 62fd105
Author: Davide Italiano <dccitaliano@gmail.com>
Date:   Thu Mar 9 11:27:41 2017 -0800

    imerge 'mymerge': automatic merge 1-648
```

I found git-imerge finish and git-imerge simplify not working for my case. Is there an easy way of "stopping" the merge here? If so, maybe should be exposed as a command?

**Comment by dcci** [comment]
I can probably create a branch, move current head then rebase and squash, but it would be nice if this was handled automatically by a command in `git imerge`

**Comment by mhagger** [comment]
What do you mean by "stop the merge where it is right now"?

If you want to put the merge on ice and come back to it later, then you don't have to do anything special. Just switch to another branch, do you work, and whenever you want to continue the imerge, type `git imerge continue`. (Of course you will lose any unstaged changes on the current micromerge.)

If you want to stop the imerge and end up in a state where whatever part of the merge you have done is kept (e.g., the branch merged with only part of master or the branch rebased not all the way to the other branch's tip but rather to some intermediate commit on the other branch), that feature wish is the subject of issue #101, and it is not yet implemented.

If your goal is a merge, you could do this manually without a huge amount of difficulty by using `git imerge reparent` to make the commit whose contents represent the merge you want have the correct parents. You would first switch to the commit with the desired tree, then run something like

    git checkout -b my-new-merge-commit $(git imerge reparent $PARENT1 $PARENT2)

then probably adjust the commit message using `git commit --amend`.

If your goal is a rebase, you could still probably finish it manually in its partial state if you are desperate, but it would involve a lot of confusing bookkeeping.

**Comment by dcci** [comment]
I mean exactly what's described in #101.
