### ISSUE TITLE
Add automated tests

### ISSUE THREAD

**Issue by pradyunsg** [mhagger/git-imerge#128]
This would probably help with easing development?

Just a thought. :)

**Comment by mhagger** [comment]
Yes, it is a very good idea. Are you willing to work on it? I'd be happy to help you get started.

**Comment by pradyunsg** [comment]
Hi @mhagger!

> Are you willing to work on it?

No, not in the near future. I've already committed my OSS time to a different project. I might just come around to this issue someday, which is why I opened this.

**Comment by pradyunsg** [comment]
Closing since doesn't look like anyone's gonna be doing this. :)
