### ISSUE TITLE
Original author not preserved for rebased commits

### ISSUE THREAD

**Issue by DEVoytas** [mhagger/git-imerge#135]
I used `--goal=border-with-history` option to merge two branches together.
There are no commits authored by me on either of those branches.

After imerge finished, commits with commit message of form:

```
Original commit message

(rebased from commit <SHA1 of org commit>)
```
which, I think correspond to the commits D1..D2 in this graph:

```
o---o---1---2---3
     \           \
      A-----------A3
       \           \
        B-----------B3
         \           \
          C-----------C3
           \           \
            D---D1--D2--D3    NEW_BRANCH
```

for some reason are now authored (not just committed, which is obvious) by myself, rather then by the original author (i.e. author of <SHA1 of org commit>).

I understand why I am the author of the commit merges (i.e A3..D3) .
This is consistent with what regular git merge does.
However for commits D1..D2, original author should be kept in my opinion, because I would not like to take credit for someones else work.
For now, I think I will manually change the commit author to the original one, but it would be nice if imerge could do it automatically some day.

EDIT:
If this is implemented, `AuthorDate` should probably be kept as well.

**Comment by mhagger** [comment]
It seems like a reasonable request to retain the authorship on commits `D1` and `D2`. Those commits don't have parent links back to the original commits `1` and `2`, so it would otherwise be hard to discover who initiated them.

It's not so clear whether `A3…C3` should be recorded as authored by the person doing the imerge. `border-with-history` is an awful lot like `rebase-with-history` and commits `A3…D3` are a lot like rebased versions of `A…D`. So maybe they _should_ retain the latter commit's original authors?

What about commit `D3`? It can be seen both as a merge commit of `C3` and `D2` but also as a rebased version of `3`. Who should be recorded as the author of that commit?

**Comment by DEVoytas** [comment]
OK, after I created this issue I noticed there already was fir for it: https://github.com/mhagger/git-imerge/pull/119
but it needed some rework.
So I reworked that PR (taking the comments into account) and created new one: https://github.com/mhagger/git-imerge/pull/137

**Comment by DEVoytas** [comment]
> It's not so clear whether `A3…C3` should be recorded as authored by the person doing the imerge.

In my opinion this should be authored by person doing the imerge, because this is basically series of regular merge commits (just merging one at a time, but it doesn't matter how many).
This is consistent with regular git behaviour, merge comment is always attributed to person actually doing a merge. Which is file because merge commit points to original commits so you don't loose any information about origin author, date, etc.

> What about commit `D3`? It can be seen both as a merge commit of `C3` and `D2` but also as a rebased version of `3`. Who should be recorded as the author of that commit?

Yeah, this one is more interesting one... I guess it can be argued both ways.
Until consensus is reached, I would suggest just go with whatever requires less complex changes in the code logic, and when some strong arguments arise for either side, the corner cases could be addressed later.

**Comment by DEVoytas** [comment]
Hmm, after looking at the code more carefully I realized that https://github.com/mhagger/git-imerge/pull/137 will not actually fix `border-with-history` case (it will only fix `rebase-with-history`).
To fix `border-with-history`, the same fix must be repeated in `simplify_to_border()`, am I right ?

**Comment by mhagger** [comment]
@DEVoytas: Thanks for your thoughts and your work. Please see #138. If you think that is a good approach, it can replace #137 (it also handles `simplify_to_border`) and it should close this issue.

**Comment by DEVoytas** [comment]
@mhagger, you are welcome, and thank you for your work on `git-imerge`, it's super useful!
I replied there: https://github.com/mhagger/git-imerge/pull/138 and agree it's more complete solution
