### ISSUE TITLE
How do I switch to a different imerge?

### ISSUE THREAD

**Issue by skestle** [mhagger/git-imerge#142]
I thought it would be simple; just checkout `refs/heads/imerge/<branch>` and then `git imerge continue`, but that jumps back to the imerge that I started last.

When checked out on the branch that I want to continue, `git imerge list` shows the last one as starred.

(While it doesn't seem that related to me, I ran into this by starting the new/"last" imerge in a different git worktree)

**Comment by skestle** [comment]
`git config imerge.default <branch>` is the solution.

As for my worktree, I've run `git config extensions.worktreeConfig true` and upgraded git to 2.21.
Then I can set `git config -- worktree imerge.default <branch>`* and then both worktrees can execute their imerges simultaneously

* theoretically - it throws an error for me, so I have to update the worktree config file manually.

**Comment by skestle** [comment]
... there's also the bit where I was trying `git imerge --name=<my-branch>` instead of `git imerge --name <my-branch>`

**Comment by mhagger** [comment]
I think you're looking for `git imerge --name=<my-branch> continue`; i.e., the `--name=` option has to be combined with an actual operation (here, `continue`) for it to work. I guess this could be clearer.

I'll close this issue, but if my suggestion doesn't work for you or if you want to suggest a documentation improvement, don't hesitate to reopen it.

**Comment by skestle** [comment]
While making the docs clearer, note you made the same mistake that I did. `--name=...`  will not work. It must be a space ;)

Also, the ability to set a bash variable etc would be very good
