### ISSUE TITLE
Cannot install if the pkg-config call fails

### ISSUE THREAD

**Issue by kergoth** [mhagger/git-imerge#153]
As the subject indicates, a failure to call pkg-config --variable=completionsdir bash-completion, as is the case if the distro doesn't have bash-completion installed, it's impossible to install the python project. Even if it succeeds, it's bad form for a setup.py to install files outside the specified installdir/prefix, particularly if that behavior can't be explicitly disabled. If I'm installing this into a virtualenv, I don't want it throwing completions outside of the virtualenv, for example.

**Comment by mhagger** [comment]
I feel your pain, but don't really know anything about pkg-config or virtualenv. Do you have an idea how to fix this problem?

**Comment by Taytay** [comment]
Is the bash-completion a necessity? From the looks of the setup script, it does not appear to be. I edited the script to handle the error more gracefully and skip it if it couldn't get the  bash-completions directory...

**Comment by mochadwi** [comment]
Have you open PR @Taytay for the script fix?

**Comment by talios** [comment]
Came to report this - glad to find it already reported. I miss having imerge.

**Comment by mochadwi** [comment]
Any possible workaround to handle this bash-completions? 

```
Package bash-completion was not found in the pkg-config search path.
Perhaps you should add the directory containing `bash-completion.pc'
to the PKG_CONFIG_PATH environment variable
No package 'bash-completion' found
Traceback (most recent call last):
  File "/private/tmp/git-imerge-20201024-34704-pokck8/git-imerge-1.2.0/setup.py", line 11, in <module>
    completionsdir = subprocess.check_output(
  File "/usr/local/Cellar/python@3.9/3.9.0/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/Cellar/python@3.9/3.9.0/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['pkg-config', '--variable=completionsdir', 'bash-completion']' returned non-zero exit status 1.

```

I'm trying to add `git-imerge` to homebrew

@mhagger
