### ISSUE TITLE
What do the numbers mean during rebase?

### ISSUE THREAD

**Issue by abitrolly** [mhagger/git-imerge#155]
When `git-imerge` prints `Autofilling 372-50` message, what exactly 372 and 50 mean?

I expected to see them on `git-imerge diagram` but they are not there.

**Comment by mhagger** [comment]
In the diagram, they indicate respectively the 372th column and the 50th row, where both of them start counting at zero.

**Comment by abitrolly** [comment]
The column are commits on the trunk? Meaning that if I rebasing against `master`, the trunk is `master` and I my branch is already 372 commits higher when when the process had started. Is that right?
