### ISSUE TITLE
Install fails on zsh

### ISSUE THREAD

**Issue by c-alpha** [mhagger/git-imerge#158]
```console
example:git-imerge$ echo $SHELL
/bin/zsh
example:git-imerge$ zsh --version
zsh 5.7.1 (x86_64-apple-darwin19.0)
example:git-imerge$ python3 --version
Python 3.8.4
example:git-imerge$ python3 setup.py install
Package bash-completion was not found in the pkg-config search path.
Perhaps you should add the directory containing `bash-completion.pc'
to the PKG_CONFIG_PATH environment variable
No package 'bash-completion' found
Traceback (most recent call last):
  File "setup.py", line 11, in <module>
    completionsdir = subprocess.check_output(
  File "/usr/local/Cellar/python@3.8/3.8.4/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/Cellar/python@3.8/3.8.4/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['pkg-config', '--variable=completionsdir', 'bash-completion']' returned non-zero exit status 1.
```

As I'm using `zsh`, I don't have `bash-completion` installed, of course.

**Comment by c-alpha** [comment]
I guess this is linked with #153 ...

**Comment by mochadwi** [comment]
Should we configure `bash_completions` side-by-side with `zsh`? btw, have you found the workaround? @c-alpha

**Comment by c-alpha** [comment]
Thanks for looking into this, @mochadwi. No. I haven't found a workaround.

I think there would be no harm in installing several shell completions in parallel; it's very little data.

What seems important is to make all shell completion packages **optional** install dependencies. i.e. to allow the install to complete successfully, even if no shell completions at all have been installed. `git-imerge` on homebrew (as mentioned [here](https://github.com/mhagger/git-imerge/issues/153#issuecomment-715660735)) would be my ideal solution, too, btw.

**Comment by mhagger** [comment]
I think this is a dup of #153, for which I just submitted PR #176. It'd be great if you tell us there whether this fixes the problem for you.

If you don't think this is a dup, feel free to reopen this issue.
