### ISSUE TITLE
Question: can git-imerge product a list of all conflicts in advance and their associated commits?

### ISSUE THREAD

**Issue by hpe-ykoehler** [mhagger/git-imerge#209]
I am looking forward to use git-imerge in our feature branch integration process.  In order to do so, and to reduce the time to resolve the conflicts, I was wondering if it would be possible to at the start of the merge generate a list of all conflicts with all associated commits so that we could create a "hook" list of people that needs to have their time reserved for this operation, so that we can summon them as needed.

I saw the git-imerge autofill command which I am not clear when and how to use it.

Thanks you.

**Comment by mhagger** [comment]
It can only determine the "merge conflict frontier" as described [here](https://softwareswirl.blogspot.com/2012/12/mapping-merge-conflict-frontier.html), which is equivalent to the list of "blocker" commits on the frontier. Those are merges that definitely have to be done by humans. You can view the "merge conflict frontier" immediately after starting an imerge by running `git imerge diagram`.

But it can't determine what will happen outside of the "merge conflict frontier", where everything might go smoothly, or perhaps other blockers will be found that also have to be merged by hand. They will only be revealed after one or more conflicts have been resolved.

Hope that helps!
