### ISSUE TITLE
Using existing file in manual merge causes "Commit %d-%d was not blocking the frontier"

### ISSUE THREAD

**Issue by ReDucTor** [mhagger/git-imerge#42]
When using an existing file in a manual merge due to incorporate_user_merge using diff-index and there being no changes required for the existing file, the git commit does not occur within the exception, so the commit remains the same and the incorrect heads are found within incorporate_manual_merge

**Comment by habnabit** [comment]
having this same problem. :C

**Comment by habnabit** [comment]
seemingly resolved by doing `git imerge continue --no-edit` instead of `git commit && git imerge continue` after resolving conflicts.

**Comment by waldyrious** [comment]
@habnabit's trick didn't work for me, but I solved the problem by adding an additional change (just whitespace adjustment) while fixing the conflict, so that there would be something to commit. I just added the file and did `git imerge continue` as usual.

**Comment by jmah** [comment]
I haven't seen this problem myself (but haven't used imerge recently); I wonder if `git commit --allow-empty` would work as well.

**Comment by mhagger** [comment]
> I haven't seen this problem myself (but haven't used imerge recently); I wonder if `git commit --allow-empty` would work as well.

@jmah: Indeed, that is the workaround that I use. In fact, I don't think that `--allow-empty` is needed, because merge commits are always allowed to be empty.

I just implemented #98, which I think should fix this problem for once and for all. It would be great if people who have experienced this problem would test it.

**Comment by talios** [comment]
+100 Have hit this a few times, sadly if the fix here works - I guess I'll not actually _notice_ ( which is a good thing - just makes testing hard ).
