### ISSUE TITLE
Equivalent of 'git rebase --skip'

### ISSUE THREAD

**Issue by moritz** [mhagger/git-imerge#57]
I'm in a situation where the resolution of a conflict would result in an empty commit. When I `git add` the file, and then do `git imerge continue` I get the message `Commit 121-302 was not blocking the frontier.`. When doing `git imerge continue`, I get the very same conflict presented again.

I've worked around this with `git commit --allow-empty`, but it would be nicer to  have `git imerge skip`, in analogy to `git rebase --skip`.

**Comment by talios** [comment]
I just ran into this again and used the `git commit --allow-empty` trick, did anything come of this change at all?

**Comment by mhagger** [comment]
PR #98 should fix the main part of this problem, though it doesn't also cause the empty commit to be omitted from the final result. (Which would probably be OK, but is not quite a no-brainer because doing so would cause the commit message to be lost.) As a workaround, I run `git rebase --interactive` after `git imerge rebase` in this situation if I need to get rid of empty commits.

**Comment by pwaller** [comment]
@mhagger thanks for this nice tool.

I just faced this situation where I'm in the middle of an `imerge rebase`, and decided I don't want the commit. It's not totally obvious what I should type after #98 was merged. I guess I can `git reset && git checkout .` to reset master, commit an empty commit, and then continue the rebase. Is that the best I can do, or do you recommend something else? (It's not clear to me that `git rebase --interactive` is a valid thing to run when I'm in the conflicted state - is it?)

**Comment by mhagger** [comment]
@pwaller: That's the best that I know of. It would *not* work to run `git rebase --interactive` while an incremental merge is in progress. But if you run it immediately afterwards, it will detect that the commit was empty and will omit it from the result.

Slightly off-topic: if you want to delete a _non-empty_ commit from the resulting history, you can use `git imerge drop`, which does an incremental merge to insert a revert commit into the history directly after the unwanted commit, then when done deletes both the original commit and the revert commit.
