### ISSUE TITLE
Consider publishing git-imerge on PyPI

### ISSUE THREAD

**Issue by ccharles** [mhagger/git-imerge#74]
It would be very helpful if `git-imerge` was available via [PyPI](https://pypi.python.org/pypi) so it could be installed via `pip` or similar tools.

**Comment by mhagger** [comment]
Yes, that would be helpful for some people. Is there somebody around who could summarize what would be needed to make `git-imerge` into a PyPI package (maybe even in the form of a PR)? Do we just need a `setup.py` file, or would we have to rearrange the sources? Every time I look into Python's packaging tools, it seems like there is no real consensus about best practices and my gumption ebbs away. Maybe that situation has changed.

**Comment by orao** [comment]
Sorry if the question has already been asked and answered but has it been considered to supply `git imerge` to the base `git` itself as a new command, or even make it a part of the `merge` command itself _(perhaps with a flag, like `-i`)_?

**Comment by abitrolly** [comment]
README says it is available from PyPI https://github.com/mhagger/git-imerge#installation but it is not - https://pypi.org/project/git-imerge/

**Comment by elonzh** [comment]
> README says it is available from PyPI https://github.com/mhagger/git-imerge#installation but it is not - https://pypi.org/project/git-imerge/

According to #143 ，I think it will be uploaded to PyPI soon. @mhagger

**Comment by Calinou** [comment]
Bump :slightly_smiling_face: I still can't install `git-imerge` using `pip`:

```text
ERROR: Could not find a version that satisfies the requirement git-imerge (from versions: none)
ERROR: No matching distribution found for git-imerge
```

**Comment by mhagger** [comment]
There is now really a release on PyPI, so this should work now. Please reopen the issue if you are still having problems.
