### ISSUE TITLE
Completion errors under bash 3.x

### ISSUE THREAD

**Issue by rhunter** [mhagger/git-imerge#86]
The bash completion script for `git-imerge` includes comments that indicate it aims for compatibility with older bashes.

#### Each completion

I tried the completion script on the bash supplied with Mac OS X (bash 3.2). It does work, but it also shows a warning message on each completion:

```
bash: words: bad array subscript
```

It seems the error comes from the expression `"${words[i-1]}"` [in the main completion function][badexpr].

On the first loop, `i` is 0 and so the expression evaluates to `${words[0-1]}`, which is equivalent to `${words[-1]}`, which was apparently invalid until bash 4.2 started allowing negative array subscripts to mean counting from the end [(reference)][stackexchange].

I don't think this code means to count from the end, though. I think that might be an accident that happens to have no obvious symptom in bash 4.2.

If I'm reading the code correctly, this is simply trying to find the word immediately preceded by "imerge" (eg "start" in "git imerge start"). We can sidestep the problem by starting the search at position 1 -- assuming that "imerge" will always be in at least the 0th position (in practice, "imerge" will almost certainly be position 1 or greater).

Once this is fixed, there's another complication that shows up.

#### Mid-command completion

Users can activate completion from any point in the command, although the very end is certainly the most common.

  $ git imerge start master

If you type a whole command like the one above, move the cursor back to the space after the command, then hit the completion key, bash 3.2 aborts the entire command line with the message:
```
bash: $index: substring expression < 0
```

(bash 4.3 doesn't throw an error, but doesn't show any completions either)

I'm still investigating this one, but it's not obvious where the error is coming from.

[stackexchange]: http://unix.stackexchange.com/a/198790/63149
[badexpr]: https://github.com/mhagger/git-imerge/commit/81d7c47ccb4680f4d3e29ea8b70c3b24875dd31d#diff-f57038d3f4682c0686ab1d78e9e1b118R253

**Comment by JeremybellEU** [comment]
This issue was already fixed in #87

**Comment by rhunter** [comment]
The changes I submitted should have fixed the first part of this
(end-of-line completion), but I don't think those changes helped the second
part (mid-line completion).

**Comment by TimvdLippe** [comment]
Ah I misunderstood. Maybe it is good to highlight in this issue what is fixed already and what isn't.

**Comment by rhunter** [comment]
Good idea. I'll edit the issue next time I get to my computer.

(or if someone beats me to it, that's fine too)

**Comment by rhunter** [comment]
Hm, maybe the changes in #87 did address both problems after all. Although mid-command completion with Bash 3.2 doesn't work perfectly, it works well enough now -- it no longer aborts with an error message.

I'll close this ticket.
