### ISSUE TITLE
Conflict without any conflicts (no markers)

### ISSUE THREAD

**Issue by kastiglione** [mhagger/git-imerge#93]
What would lead to `git-imerge` stopping and saying two commits have conflicts, but the one file marked as being modified by both branches has no actual conflict markers in it?

**Comment by johnkeeping** [comment]
Do you have git-rerere enabled?  If it has automatically resolved the conflict the file will still be marked as conflicted in the index.

**Comment by kastiglione** [comment]
I've never used or turned on rerere.

**Comment by kastiglione** [comment]
So apparently `rerere` was previously used in this repo, and apparently that info gets included as part of the clone. TIL.

**Comment by kastiglione** [comment]
Thanks @johnkeeping :ok_hand:
