### ISSUE TITLE
Question: is --goal required if it coincides with the initial command?

### ISSUE THREAD

**Issue by waldyrious** [mhagger/git-imerge#99]
I.e, if I do `git imerge rebase <target-root-branch>`, do I have to finish with `git imerge finish --goal=rebase`, or can I just do `git imerge finish`? If the latter's the case, then when should I use `--goal` in the `finish` subcommand? Perhaps it's for if I change my mind mid-imerge about whether I want a merge or rebase?

**Comment by mhagger** [comment]
Sorry @waldyrious, I missed the notification for your question.

You're right; `--goal` is only needed on the `git imerge finish` command if you change your mind about the goal while you are working.

Feel free to reopen this issue if you have any followup questions.

**Comment by waldyrious** [comment]
That's what I thought, thanks for confirming :)

For reference, my question was due to the instructions as written in http://softwareswirl.blogspot.pt/2013/05/git-imerge-practical-introduction.html (which is linked in the README):

> When you are done, simplify the incremental merge into a simple merge, a simple rebase, or a rebase-with-history:
> `$ git imerge finish --goal=merge`

If you'd like, clarifying that section of the post would probably prevent others from having this same question.
